// components/portfolio/Hero.tsx
'use client'
import { useRef, useState } from 'react'
import { useScrollY } from '@/hooks/useParallax'
import { Camera, Github, User } from 'lucide-react'

const techs = [
  'Angular', 'React', 'TypeScript', 'Node.js',
  'Go', 'PostgreSQL', 'Redis', 'Docker', 'Auth0', 'Cypress',
]

export default function Hero() {
  const scrollY = useScrollY()
  const fileRef = useRef<HTMLInputElement>(null)
  const [photoUrl, setPhotoUrl] = useState<string | null>(null)

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return
    const reader = new FileReader()
    reader.onload = (ev) => setPhotoUrl(ev.target?.result as string)
    reader.readAsDataURL(file)
  }

  return (
    <section
      id="home"
      className="relative min-h-screen flex flex-col items-center justify-center overflow-hidden px-6"
    >
      {/* Parallax blobs */}
      <div
        className="parallax-layer absolute top-1/4 left-1/4 w-[500px] h-[500px] rounded-full pointer-events-none"
        style={{
          background: 'radial-gradient(circle, rgba(99,102,241,0.13) 0%, transparent 65%)',
          transform: `translateY(${scrollY * 0.35}px)`,
        }}
        aria-hidden="true"
      />
      <div
        className="parallax-layer absolute bottom-1/4 right-1/4 w-80 h-80 rounded-full pointer-events-none"
        style={{
          background: 'radial-gradient(circle, rgba(129,140,248,0.09) 0%, transparent 65%)',
          transform: `translateY(${scrollY * 0.2}px)`,
        }}
        aria-hidden="true"
      />
      <div
        className="parallax-layer absolute top-10 right-10 w-40 h-40 rounded-full pointer-events-none"
        style={{
          background: 'radial-gradient(circle, rgba(99,102,241,0.06) 0%, transparent 70%)',
          transform: `translateY(${scrollY * 0.5}px)`,
        }}
        aria-hidden="true"
      />

      {/* Content */}
      <div className="relative z-10 flex flex-col items-center text-center max-w-4xl mx-auto">

        {/* Photo circle */}
        <div className="mb-10 animate-float">
          <div className="relative w-40 h-40 group cursor-pointer animate-pulse-glow" onClick={() => fileRef.current?.click()}>
            {/* Decorative rings */}
            <div className="absolute inset-0 rounded-full border-2 border-accent/40 scale-110 group-hover:scale-125 transition-transform duration-500" />
            <div className="absolute inset-0 rounded-full border border-accent/20 scale-125 group-hover:scale-150 transition-transform duration-700" />

            {/* Photo or placeholder */}
            {photoUrl ? (
              <>
                <img
                  src={photoUrl}
                  alt="Vinay KR profile photo"
                  className="w-full h-full rounded-full object-cover border-2 border-accent/60"
                />
                <div className="absolute inset-0 rounded-full bg-void/60 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                  <Camera className="w-7 h-7 text-frost" />
                </div>
              </>
            ) : (
              <div className="w-full h-full rounded-full bg-surface border-2 border-border flex flex-col items-center justify-center gap-1.5 group-hover:border-accent/50 transition-colors duration-300">
                <User className="w-8 h-8 text-muted group-hover:text-accent transition-colors" />
                <span className="text-xs text-muted group-hover:text-accent transition-colors font-medium leading-tight px-2">
                  Upload Photo
                </span>
              </div>
            )}
          </div>
          <input
            ref={fileRef}
            type="file"
            accept="image/*"
            className="hidden"
            onChange={handleFileChange}
          />
        </div>

        {/* Name & title */}
        <div className="animate-fade-in-up" style={{ animationDelay: '0.1s', opacity: 0 }}>
          <p className="text-accent font-mono text-sm tracking-widest mb-3 uppercase">
            Full Stack Developer
          </p>
          <h1 className="text-5xl md:text-7xl lg:text-8xl font-display font-bold leading-none mb-4">
            <span className="gradient-text">Vinay KR</span>
          </h1>
          <p className="text-muted text-lg md:text-xl max-w-2xl mx-auto leading-relaxed mt-4">
            Building production-grade applications across{' '}
            <span className="text-frost font-medium">FinTech</span>,{' '}
            <span className="text-frost font-medium">Web3 Custody</span>, and{' '}
            <span className="text-frost font-medium">Casino Gaming</span> domains
            with 3+ years of experience.
          </p>
        </div>

        {/* Tech badges */}
        <div
          className="flex flex-wrap justify-center gap-2 mt-8 animate-fade-in-up"
          style={{ animationDelay: '0.3s', opacity: 0 }}
        >
          {techs.map(tech => (
            <span
              key={tech}
              className="px-3 py-1 rounded-full text-xs font-medium bg-surface border border-border text-muted hover:border-accent/50 hover:text-frost transition-all duration-200"
            >
              {tech}
            </span>
          ))}
        </div>

        {/* CTAs */}
        <div
          className="flex flex-col sm:flex-row gap-4 mt-10 animate-fade-in-up"
          style={{ animationDelay: '0.5s', opacity: 0 }}
        >
          <a
            href="#projects"
            className="px-8 py-3.5 rounded-xl bg-accent hover:bg-accent-glow text-frost font-semibold text-sm transition-all duration-200 hover:shadow-2xl hover:-translate-y-0.5"
          >
            View Projects
          </a>
          <a
            href="https://github.com/vi-nayKR"
            target="_blank"
            rel="noopener noreferrer"
            className="px-8 py-3.5 rounded-xl border border-border hover:border-accent/50 text-frost font-semibold text-sm transition-all duration-200 hover:bg-surface hover:-translate-y-0.5 flex items-center justify-center gap-2"
          >
            <Github className="w-4 h-4" />
            GitHub
          </a>
        </div>

        {/* Scroll indicator */}
        <div
          className="mt-16 flex flex-col items-center gap-2 text-muted animate-fade-in-up"
          style={{ animationDelay: '0.7s', opacity: 0 }}
        >
          <span className="text-xs font-mono tracking-widest uppercase">Scroll</span>
          <div className="w-px h-10 bg-gradient-to-b from-accent to-transparent animate-pulse" />
        </div>
      </div>
    </section>
  )
}

// src/app/components/hero/hero.component.ts
import { Component, HostListener, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TiltDirective } from '../../directives/tilt.directive';
import { Model3dComponent } from '../model3d/model3d.component';
import { PHOTO_BASE64 } from './photo-data';

@Component({
  selector: 'app-hero',
  standalone: true,
  imports: [CommonModule, TiltDirective, Model3dComponent],
  template: `
    <section
      id="home"
      class="relative min-h-screen flex flex-col items-center justify-center overflow-hidden px-4 md:px-6 pt-32 pb-16 md:pt-40 md:pb-24"
    >
      <!-- Huge Parallax Background Text -->
      <div
        class="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 outline-bg-text select-none pointer-events-none transition-transform duration-300 ease-out"
        [style.transform]="'translate3d(calc(-50% + ' + (mouseX() * -0.04) + 'px), calc(-50% + ' + (parallaxY() * -0.22) + 'px), 0)'"
        style="opacity: 0.25;"
      >
        VINAY KR
      </div>

      <!-- Parallax background blobs -->
      <div
        class="absolute top-1/4 left-1/4 w-96 h-96 rounded-full pointer-events-none transition-transform duration-300 ease-out"
        [style.background]="'radial-gradient(circle, rgba(99,102,241,0.12) 0%, transparent 70%)'"
        [style.transform]="'translate3d(' + (mouseX() * 0.05) + 'px, ' + (parallaxY() * 0.45) + 'px, 0)'"
      ></div>
      <div
        class="absolute bottom-1/4 right-1/4 w-72 h-72 rounded-full pointer-events-none transition-transform duration-300 ease-out"
        [style.background]="'radial-gradient(circle, rgba(129,140,248,0.08) 0%, transparent 70%)'"
        [style.transform]="'translate3d(' + (mouseX() * -0.05) + 'px, ' + (parallaxY() * 0.22) + 'px, 0)'"
      ></div>

      <!-- Floating Interactive Code Tags -->
      @for (tag of floatingTags; track tag.text) {
        <div
          (click)="scrollToSection(tag.target)"
          (mouseenter)="hoveredTag.set(tag.text)"
          (mouseleave)="hoveredTag.set(null)"
          class="absolute pointer-events-auto text-accent/70 hover:text-accent font-mono text-xs md:text-sm border border-accent/25 hover:border-accent/70 px-4 py-2 rounded-xl select-none backdrop-blur-[4px] bg-void/25 shadow-sm hover:shadow-xl hover:shadow-accent/15 cursor-pointer transition-all duration-300 ease-out hidden sm:block"
          [style.top]="tag.top"
          [style.left]="tag.left"
          [style.transform]="'translate3d(' + (mouseX() * tag.speedX) + 'px, ' + (mouseY() * tag.speedY + parallaxY() * (tag.speedY * 4.5)) + 'px, 0) scale(' + (hoveredTag() === tag.text ? '1.12' : '1') + ')'"
        >
          {{ tag.text }}
        </div>
      }

      <div class="relative z-10 max-w-6xl w-full mx-auto flex flex-col md:flex-row items-center justify-between gap-12 flex-1">
        <!-- Left Column: Name & Title Greeting (55%) -->
        <div class="w-full md:w-[55%] flex flex-col items-center md:items-start text-center md:text-left">
          
          <div class="animate-fade-in-up" style="animation-delay:0.1s; opacity:0;">
            <h1 class="text-4xl md:text-6xl font-display font-bold leading-none mb-6 text-frost">
              👋 Hi, I'm <span class="gradient-text">Vinay</span>!
            </h1>
            <p class="text-accent font-mono text-xs md:text-sm tracking-widest mb-4 uppercase">Full Stack Developer</p>
            <p class="text-muted text-lg md:text-xl max-w-2xl mx-auto md:mx-0 leading-relaxed mt-4">
              Building production-grade applications across
              <span class="text-frost font-medium">FinTech</span>,
              <span class="text-frost font-medium">Web3 Custody</span>, and
              <span class="text-frost font-medium">Casino Gaming</span> domains
              with 3+ years of experience.
            </p>
          </div>

          <!-- Tech badges -->
          <div class="flex flex-wrap justify-center md:justify-start gap-2 mt-8 animate-fade-in-up" style="animation-delay:0.3s; opacity:0;">
            @for (tech of techs; track tech) {
              <span class="px-3 py-1 rounded-full text-xs font-medium bg-surface border border-border text-muted hover:border-accent/50 hover:text-frost transition-all duration-200">
                {{ tech }}
              </span>
            }
          </div>

          <!-- CTA Buttons -->
          <div class="flex flex-col sm:flex-row gap-4 mt-10 animate-fade-in-up" style="animation-delay:0.5s; opacity:0;">
            <a
              href="#projects"
              class="px-8 py-3.5 rounded-xl bg-accent hover:bg-accent-glow text-frost font-semibold text-sm transition-all duration-200 hover:shadow-xl hover:shadow-accent/25 hover:-translate-y-0.5 text-center"
            >
              View Projects
            </a>
            <a
              href="https://github.com/vi-nayKR"
              target="_blank"
              rel="noopener noreferrer"
              class="px-8 py-3.5 rounded-xl border border-border hover:border-accent/50 text-frost font-semibold text-sm transition-all duration-200 hover:bg-surface hover:-translate-y-0.5 flex items-center justify-center gap-2"
            >
              <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                <path d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"/>
              </svg>
              GitHub
            </a>
          </div>
        </div>

        <!-- Right Column: Interactive 3D Model with Overlaying Profile Photo (45%) -->
        <div class="w-full md:w-[45%] flex items-center justify-center relative min-h-[400px] md:min-h-[500px]">
          <!-- Interactive 3D WebGL Layer -->
          <div class="absolute inset-0 z-0">
            <app-model3d></app-model3d>
          </div>

          <!-- Profile Photo floating in center of 3D gyroscope system -->
          <div class="relative z-10 pointer-events-none animate-float" style="animation-delay: 0s;">
            <div
              class="relative w-40 h-40 md:w-48 md:h-48 rounded-full animate-pulse-glow border border-accent/20 overflow-hidden"
              style="background: radial-gradient(circle, var(--color-surface) 0%, var(--color-abyss) 100%);"
            >
              <!-- Ring decorations -->
              <div class="absolute inset-0 rounded-full border-2 border-accent/40 scale-110 transition-transform duration-500"></div>
              <div class="absolute inset-0 rounded-full border border-accent/20 scale-125 transition-transform duration-700"></div>

              <!-- Photo -->
              <img
                [src]="photoUrl()"
                alt="Vinay KR"
                class="w-full h-full rounded-full object-cover p-1.5 border-2 border-accent/60"
                style="object-position: center top;"
              />
            </div>
          </div>
        </div>
      </div>

      <!-- Scroll indicator (absolute bottom) -->
      <div class="relative z-10 mt-16 flex flex-col items-center gap-2 text-muted animate-fade-in-up" style="animation-delay:0.7s; opacity:0;">
        <span class="text-xs font-mono tracking-widest uppercase">Scroll</span>
        <div class="w-px h-10 bg-gradient-to-b from-accent to-transparent animate-pulse"></div>
      </div>
    </section>
  `,
})
export class HeroComponent {
  photoUrl = signal<string>(PHOTO_BASE64);
  parallaxY = signal(0);
  mouseX = signal(0);
  mouseY = signal(0);
  hoveredTag = signal<string | null>(null);

  techs = ['Angular', 'React', 'TypeScript', 'Node.js', 'Go', 'PostgreSQL', 'Redis', 'Docker', 'Auth0', 'Cypress'];

  floatingTags = [
    { text: '<Code />', top: '22%', left: '10%', speedX: 0.05, speedY: 0.04, target: 'projects' },
    { text: 'Go', top: '16%', left: '78%', speedX: -0.06, speedY: 0.03, target: 'skills' },
    { text: 'RxJS', top: '68%', left: '8%', speedX: 0.04, speedY: -0.05, target: 'skills' },
    { text: '2FA', top: '78%', left: '80%', speedX: -0.05, speedY: 0.03, target: 'skills' },
    { text: '{...}', top: '42%', left: '86%', speedX: 0.03, speedY: -0.04, target: 'skills' },
    { text: 'Angular', top: '82%', left: '22%', speedX: -0.03, speedY: 0.05, target: 'skills' },
  ];

  @HostListener('window:scroll')
  onScroll() {
    this.parallaxY.set(window.scrollY);
  }

  @HostListener('window:mousemove', ['$event'])
  onMouseMove(event: MouseEvent) {
    this.mouseX.set(event.clientX - window.innerWidth / 2);
    this.mouseY.set(event.clientY - window.innerHeight / 2);
  }

  scrollToSection(targetId: string) {
    if (typeof document === 'undefined') return;
    const el = document.getElementById(targetId);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth' });
    }
  }
}
